# NOTE: These settings can be overridden by environment variables as well, in
# particular:
#
#    PGHOST
#    PGPORT
#    PGUSER
#    PGPASS
#    PGDATABASE

Default: &defaults
  user: master_yesod
  password: EfK&-{-(
  host: portal.chiqoi8zcqr0.eu-west-1.rds.amazonaws.com
  port: 5432
  database: yesod_portal
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: yesod_portal_test
  <<: *defaults

Staging:
  database: yesod_portal_staging
  poolsize: 100
  <<: *defaults

Production:
  database: yesod_portal_production
  poolsize: 100
  <<: *defaults
