# NOTE: These settings can be overridden by environment variables as well, in
# particular:
#
#    PGHOST
#    PGPORT
#    PGUSER
#    PGPASS
#    PGDATABASE

Default: &defaults
  user: webserver2
  password: webserver2
  host: localhost
  port: 5432
  database: webserver2
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: webserver2_test
  <<: *defaults

Staging:
  database: webserver2_staging
  poolsize: 100
  <<: *defaults

Production:
  database: webserver2_production
  poolsize: 100
  <<: *defaults
